require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitorUsersController do

  # This should return the minimal set of attributes required to create a valid
  # VisitorUser. As you add validations to VisitorUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitorUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all visitor_users as @visitor_users" do
      visitor_user = VisitorUser.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:visitor_users)).to eq([visitor_user])
    end
  end

  describe "GET show" do
    it "assigns the requested visitor_user as @visitor_user" do
      visitor_user = VisitorUser.create! valid_attributes
      get :show, {:id => visitor_user.to_param}, valid_session
      expect(assigns(:visitor_user)).to eq(visitor_user)
    end
  end

  describe "GET new" do
    it "assigns a new visitor_user as @visitor_user" do
      get :new, {}, valid_session
      expect(assigns(:visitor_user)).to be_a_new(VisitorUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested visitor_user as @visitor_user" do
      visitor_user = VisitorUser.create! valid_attributes
      get :edit, {:id => visitor_user.to_param}, valid_session
      expect(assigns(:visitor_user)).to eq(visitor_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VisitorUser" do
        expect {
          post :create, {:visitor_user => valid_attributes}, valid_session
        }.to change(VisitorUser, :count).by(1)
      end

      it "assigns a newly created visitor_user as @visitor_user" do
        post :create, {:visitor_user => valid_attributes}, valid_session
        expect(assigns(:visitor_user)).to be_a(VisitorUser)
        expect(assigns(:visitor_user)).to be_persisted
      end

      it "redirects to the created visitor_user" do
        post :create, {:visitor_user => valid_attributes}, valid_session
        expect(response).to redirect_to(VisitorUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visitor_user as @visitor_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorUser.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_user => { "email" => "invalid value" }}, valid_session
        expect(assigns(:visitor_user)).to be_a_new(VisitorUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorUser.any_instance.stub(:save).and_return(false)
        post :create, {:visitor_user => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visitor_user" do
        visitor_user = VisitorUser.create! valid_attributes
        # Assuming there are no other visitor_users in the database, this
        # specifies that the VisitorUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(VisitorUser).to receive(:update).with({ "email" => "MyString" })
        put :update, {:id => visitor_user.to_param, :visitor_user => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested visitor_user as @visitor_user" do
        visitor_user = VisitorUser.create! valid_attributes
        put :update, {:id => visitor_user.to_param, :visitor_user => valid_attributes}, valid_session
        expect(assigns(:visitor_user)).to eq(visitor_user)
      end

      it "redirects to the visitor_user" do
        visitor_user = VisitorUser.create! valid_attributes
        put :update, {:id => visitor_user.to_param, :visitor_user => valid_attributes}, valid_session
        expect(response).to redirect_to(visitor_user)
      end
    end

    describe "with invalid params" do
      it "assigns the visitor_user as @visitor_user" do
        visitor_user = VisitorUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_user.to_param, :visitor_user => { "email" => "invalid value" }}, valid_session
        expect(assigns(:visitor_user)).to eq(visitor_user)
      end

      it "re-renders the 'edit' template" do
        visitor_user = VisitorUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitorUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => visitor_user.to_param, :visitor_user => { "email" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visitor_user" do
      visitor_user = VisitorUser.create! valid_attributes
      expect {
        delete :destroy, {:id => visitor_user.to_param}, valid_session
      }.to change(VisitorUser, :count).by(-1)
    end

    it "redirects to the visitor_users list" do
      visitor_user = VisitorUser.create! valid_attributes
      delete :destroy, {:id => visitor_user.to_param}, valid_session
      expect(response).to redirect_to(visitor_users_url)
    end
  end

end
